version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    networks:
      - mynetwork

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
